import {test} from 'node:test';
import assert from 'node:assert/strict';
import {BALANCE, BUILDINGS, emptyInventory} from '../src/config';
import {build,commit,expand,gather,newGame,remove,restore,save,setRoute,tick,upgrade,type GameState} from '../src/simulation';
const rich=()=>{const s=newGame();s.stock={ore:10000,ingot:10000,gear:10000};return s;};
function chain(){const s=rich();assert.ok(build(s,'drill',0,0).ok);assert.ok(build(s,'smelter',0,1).ok);assert.ok(build(s,'workshop',0,2).ok);return s;}
function route(){const s=chain();assert.ok(expand(s,1).ok);assert.ok(build(s,'dock',0,3).ok);assert.ok(build(s,'dock',1,0).ok);assert.ok(setRoute(s,1,0,'ore',10).ok);s.islands[1].inventory.ore=35;for(const b of s.buildings)b.paused=true;return s;}
const total=(s:GameState)=>s.stock.ore+s.islands.reduce((a,i)=>a+i.inventory.ore,0)+s.routes.reduce((a,r)=>a+(r.resource==='ore'?r.cargo:0),0);
test('manual gathering, stockpile commitment and build cost are separate',()=>{const s=newGame();for(let i=0;i<6;i++){assert.ok(gather(s,0).ok);tick(s,.3);}assert.equal(s.islands[0].inventory.ore,12);assert.equal(build(s,'drill',0,0).ok,false);assert.ok(commit(s,0,'ore',12).ok);assert.ok(build(s,'drill',0,0).ok);assert.equal(s.stock.ore,0);assert.equal(s.islands[0].inventory.ore,0);assert.equal(build(s,'drill',0,0).ok,false);});
test('unaffordable and locked actions do not mutate state',()=>{const s=newGame(),before=save(s);assert.equal(build(s,'smelter',0,0).ok,false);assert.equal(build(s,'drill',1,0).ok,false);assert.equal(expand(s,2).ok,false);assert.equal(save(s),before);assert.equal(commit(s,0,'ore',NaN).ok,false);assert.equal(commit(s,0,'ore',-1).ok,false);});
test('recipes conserve weighted material and pause without inputs',()=>{const s=chain();tick(s,90);const inv=s.islands[0].inventory;assert.equal(inv.ore+inv.ingot*2+inv.gear*6,60);assert.ok(inv.gear>0);assert.ok(Object.values(inv).every(v=>v>=0));const drill=s.buildings.find(b=>b.type==='drill')!;drill.paused=true;tick(s,300);assert.equal(s.buildings.find(b=>b.type==='smelter')!.active,false);assert.equal(s.buildings.find(b=>b.type==='workshop')!.active,false);});
test('timestep has consistent production across frame rates',()=>{const a=chain(),b=restore(save(a))!;tick(a,60);for(let i=0;i<600;i++)tick(b,.1);assert.deepEqual(a.islands,b.islands);assert.deepEqual(a.buildings.map(b=>b.cycles),b.buildings.map(b=>b.cycles));});
test('all machines have three distinct upgrade levels and invested-cost refunds',()=>{const s=chain();for(const b of [...s.buildings].filter(b=>b.type!=='hq')){assert.ok(upgrade(s,b.id).ok);assert.ok(upgrade(s,b.id).ok);assert.equal(b.level,3);assert.equal(upgrade(s,b.id).ok,false);const before={...s.stock};assert.ok(remove(s,b.id).ok);for(const r of ['ore','ingot','gear'] as const)assert.equal(s.stock[r],before[r]+Math.floor(b.invested[r]*BALANCE.refund));}assert.equal(remove(s,1).ok,false);});
test('bridges open land without moving inventory; shared funds establish outpost',()=>{const s=chain();s.islands[0].inventory.ore=19;assert.ok(expand(s,1).ok);assert.deepEqual(s.islands[1].inventory,emptyInventory());assert.equal(s.islands[0].inventory.ore,19);assert.ok(build(s,'drill',1,0).ok);assert.ok(s.milestones.outpost);tick(s,3);assert.equal(s.islands[1].inventory.ore,2);assert.equal(build(s,'beacon',0,4).ok,false);});
test('cargo is finite, leaves source at departure, and survives reload mid-flight',()=>{const s=route();const start=total(s);tick(s,4);assert.equal(s.routes[0].phase,'outbound');assert.equal(s.routes[0].cargo,12);assert.equal(s.islands[1].inventory.ore,23);assert.equal(total(s),start);tick(s,5);const reloaded=restore(save(s))!;assert.ok(reloaded);tick(reloaded,7);assert.equal(reloaded.routes[0].phase,'returning');assert.equal(reloaded.islands[0].inventory.ore,12);assert.equal(reloaded.routes[0].cargo,0);assert.equal(reloaded.deliveries,1);assert.equal(total(reloaded),start);tick(reloaded,80);assert.equal(reloaded.islands[1].inventory.ore,10);assert.equal(total(reloaded),start);});
test('docks cannot be removed or retargeted during flight; paused flights still arrive',()=>{const s=route();tick(s,5);const dock=s.buildings.find(b=>b.type==='dock'&&b.island===1)!;assert.equal(remove(s,dock.id).ok,false);assert.equal(setRoute(s,1,0,'gear',5).ok,false);s.routes[0].enabled=false;tick(s,30);assert.equal(s.deliveries,1);assert.equal(s.routes[0].phase,'waiting');assert.ok(remove(s,dock.id).ok);assert.equal(s.routes.length,0);});
test('save restores all economic state and rejects broken or corrupt fixtures',()=>{const s=route();tick(s,6);assert.deepEqual(restore(save(s)),s);assert.equal(restore('{no'),null);const dup=JSON.parse(save(s));dup.buildings.push(dup.buildings[0]);assert.equal(restore(JSON.stringify(dup)),null);const bad=JSON.parse(save(s));bad.routes[0].cargo=13;assert.equal(restore(JSON.stringify(bad)),null);const negative=JSON.parse(save(s));negative.islands[0].inventory.ore=-1;assert.equal(restore(JSON.stringify(negative)),null);});
test('first beacon requires an outpost and actual delivery; third island and continued building work',()=>{const s=route();assert.equal(build(s,'beacon',0,4).ok,false);assert.ok(build(s,'drill',1,1).ok);tick(s,16);assert.ok(build(s,'beacon',0,4).ok);assert.ok(s.beacon);assert.ok(expand(s,2).ok);assert.ok(build(s,'drill',2,0).ok);assert.equal(build(s,'beacon',2,1).ok,false);});

test('placement preview and purchase share the same constraints',async()=>{const {placementReason}=await import('../src/simulation');const s=route();assert.match(placementReason(s,'dock',0,5),/One drone dock/);assert.equal(build(s,'dock',0,5).ok,false);assert.match(placementReason(s,'drill',0,0),/occupied/);assert.match(placementReason(s,'drill',2,0),/bridge/);});
test('all three resource types transfer exactly with a source reserve',()=>{for(const resource of ['ore','ingot','gear'] as const){const s=route();s.islands[0].inventory=emptyInventory();s.islands[1].inventory=emptyInventory();s.islands[1].inventory[resource]=17;assert.ok(setRoute(s,1,0,resource,5).ok);tick(s,16);assert.equal(s.islands[0].inventory[resource],12);assert.equal(s.islands[1].inventory[resource],5);assert.equal(s.routes[0].cargo,0);tick(s,60);assert.equal(s.deliveries,1);}});
test('rate display measures recipes without counting stockpile transfers',async()=>{const {netRates}=await import('../src/simulation');const s=rich();build(s,'drill',0,0);tick(s,30);assert.equal(Math.round(netRates(s,0).ore),40);commit(s,0,'ore');assert.equal(Math.round(netRates(s,0).ore),40);s.buildings[1].paused=true;tick(s,31);assert.equal(netRates(s,0).ore,0);});
