import { BALANCE, BUILDINGS, ISLANDS, LEVEL_MULTIPLIER, RESOURCE, RESOURCES, upgradeCost, type BuildingType, type Cost, type Resource } from './config';
import { canAfford, expansionReason, machineStatus, netRates, unlockReason, type GameState } from './simulation';
export const icons:Record<string,string>={mountain:'M3 20 10 6l4 7 3-5 5 12H3Zm4-8 3 2 2-3',layers:'m3 8 9-5 9 5-9 5-9-5Zm0 5 9 5 9-5M3 18l9 5 9-5',settings:'M9 3h6l1 4 4 1 1 5-3 3v4l-5 1-3-3-4-1-2-5 3-3 2-6Zm7 9a4 4 0 1 1-8 0 4 4 0 0 1 8 0',house:'m3 10 9-7 9 7v11H3V10Zm6 11v-8h6v8',drill:'M5 3h14v5H5V3Zm7 5v12m-4-9 8 3m-8 1 8 3m-6 2 2 2 2-2',flame:'M12 2c2 6 8 7 8 13a8 8 0 0 1-16 0c0-3 2-6 5-8 0 3 1 4 2 5 3-3 2-7 1-10Z',send:'m3 3 19 8-9 3-3 8-7-19Zm0 0 10 11',sparkles:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7Z',box:'m3 7 9-4 9 4v11l-9 4-9-4V7Zm0 0 9 5 9-5M12 12v10',arrow:'M5 12h14m-5-5 5 5-5 5',chevron:'m8 5 7 7-7 7',check:'m5 12 4 4L20 5',lock:'M6 10h12v11H6V10Zm3 0V6a3 3 0 0 1 6 0v4',close:'m6 6 12 12M6 18 18 6',help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4m0 3v1M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',compass:'m16 8-3 5-5 3 3-5 5-3Zm6 4a10 10 0 1 1-20 0 10 10 0 0 1 20 0',pause:'M8 5v14M16 5v14',play:'m7 4 13 8-13 8V4Z',trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',plus:'M12 5v14M5 12h14',bridge:'M3 20V4m18 16V4M3 8c6 7 12 7 18 0M3 17h18M8 12v5m8-5v5',save:'M4 3h14l3 3v15H3V3h1Zm3 0v6h10V3M7 21v-8h10v8',sun:'M12 3v2m0 14v2M3 12h2m14 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2m1 5a6 6 0 1 1-12 0 6 6 0 0 1 12 0',volume:'M4 9h4l5-5v16l-5-5H4V9Zm13-1c3 3 3 5 0 8'};
export function icon(name:string,cls=''){return `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]??icons.box}"/></svg>`;}
export function costHtml(cost:Cost,s?:GameState){return RESOURCES.filter(r=>cost[r]).map(r=>`<span class="cost-item ${s&&!canAfford(s.stock,{[r]:cost[r]})?'short':''}" title="${RESOURCE[r].name}">${icon(RESOURCE[r].icon)}${cost[r]}</span>`).join('');}
export interface UIActions {action:(name:string,data:DOMStringMap)=>void;route:(target:number,resource:Resource,reserve:number)=>void}
export class UI {
  island=0;selected:number|null=null;placement:BuildingType|null=null;panel='';checklist=false;private root:HTMLElement;private panelKey='';private menuKey='';private objectiveKey='';private lastNotice=0;
  constructor(root:HTMLElement,actions:UIActions){this.root=root;root.innerHTML=`
    <header class="topbar"><button class="brand" data-action="home" aria-label="Return to home view"><span class="brand-mark">${icon('layers')}</span><span>FLOATING ISLAND<span class="brand-small">F A C T O R Y</span></span></button>
      <div class="resource-strip"><button class="island-switch" data-action="map"><span class="tiny-label">LOCAL INVENTORY</span><span id="active-island">Hearth Island</span>${icon('chevron')}</button><div id="resources"></div><button class="stock-shortcut" data-action="stock" title="Headquarters construction stockpile">${icon('box')}<span>Stockpile</span></button></div>
      <div class="top-actions"><span class="saved" id="saved">${icon('check')} Saved</span><button class="icon-button" data-action="map" title="Islands" aria-label="Islands">${icon('compass')}</button><button class="icon-button" data-action="help" title="Controls & help" aria-label="Controls and help">${icon('help')}</button><button class="icon-button" data-action="settings" title="Settings" aria-label="Settings">${icon('settings')}</button></div>
    </header>
    <aside class="objectives" id="objectives"></aside>
    <div class="island-labels" id="island-labels">${ISLANDS.map(i=>`<button class="island-label" data-action="island" data-island="${i.id}" id="label-${i.id}"><span class="island-label-name">${i.name}</span><span class="island-label-detail"></span></button>`).join('')}</div>
    <div class="deposit-label" id="deposit-label"><button data-action="gather">${icon('mountain')} Gather iron <span>+2</span></button></div>
    <aside class="side-panel" id="side-panel" hidden></aside>
    <div class="placement-banner" id="placement-banner" hidden></div>
    <div class="toast" role="status" aria-live="polite" id="toast"></div>
    <footer class="bottom-ui"><button class="stock-card" data-action="stock"><span class="stock-card-icon">${icon('box')}</span><span><span class="tiny-label">HEADQUARTERS</span><strong>Construction stockpile</strong><span class="stock-totals" id="stock-totals"></span></span>${icon('chevron')}</button><div class="build-dock"><div class="build-heading"><span>BUILD YOUR LITTLE INDUSTRY</span><span id="build-status">Choose a building, then a pad</span></div><div class="build-menu" id="build-menu"></div></div><div class="camera-note">${icon('compass')}<span>Drag to orbit · Scroll to zoom<br><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> to explore</span></div></footer>
    <dialog id="confirmation"><div class="dialog-icon">${icon('help')}</div><h2 id="confirm-title"></h2><p id="confirm-body"></p><div class="dialog-actions"><button class="secondary" id="confirm-cancel">Cancel</button><button class="primary danger" id="confirm-ok">Confirm</button></div></dialog>
    <div class="vignette"></div>`;
    root.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(b&&!b.hasAttribute('disabled'))actions.action(b.dataset.action!,b.dataset);});
    root.addEventListener('submit',e=>{if((e.target as HTMLElement).id==='route-form'){e.preventDefault();const f=new FormData(e.target as HTMLFormElement);actions.route(Number(f.get('target')),f.get('resource') as Resource,Number(f.get('reserve')));}});
  }
  toast(message:string,error=false){if(!message)return;const el=this.root.querySelector<HTMLElement>('#toast')!;el.innerHTML=`${icon(error?'help':'check')}<span>${message}</span>`;el.className=`toast show ${error?'error':''}`;this.lastNotice=Date.now();setTimeout(()=>{if(Date.now()-this.lastNotice>=3200)el.classList.remove('show');},3300);}
  saved(ok:boolean){this.root.querySelector('#saved')!.innerHTML=`${icon(ok?'check':'help')} ${ok?'Saved':'Save unavailable'}`;}
  async confirm(title:string,body:string,label:string,acknowledge=false):Promise<boolean>{const d=this.root.querySelector<HTMLDialogElement>('#confirmation')!;this.root.querySelector('#confirm-title')!.textContent=title;this.root.querySelector('#confirm-body')!.textContent=body;this.root.querySelector('#confirm-ok')!.textContent=label;this.root.querySelector<HTMLButtonElement>('#confirm-cancel')!.hidden=acknowledge;this.root.querySelector('.dialog-icon')!.innerHTML=icon(acknowledge?'sparkles':'help');d.showModal();return new Promise(resolve=>{const finish=(v:boolean)=>{d.close();resolve(v);};this.root.querySelector<HTMLButtonElement>('#confirm-cancel')!.onclick=()=>finish(false);this.root.querySelector<HTMLButtonElement>('#confirm-ok')!.onclick=()=>finish(true);d.oncancel=e=>{e.preventDefault();finish(false);};});}
  render(s:GameState){const inv=s.islands[this.island].inventory,rates=netRates(s,this.island);this.root.querySelector('#active-island')!.textContent=ISLANDS[this.island].name;
    this.root.querySelector('#resources')!.innerHTML=RESOURCES.map(r=>`<div class="resource ${r}" title="Net machine production over the last 30 seconds"><span class="resource-icon">${icon(RESOURCE[r].icon)}</span><span><span class="resource-name">${RESOURCE[r].name}</span><span class="resource-value">${Math.floor(inv[r]).toLocaleString()}<small class="${rates[r]<0?'negative':''}">${rates[r]>=0?'+':''}${rates[r].toFixed(0)}<span>/min</span></small></span></span></div>`).join('');
    this.root.querySelector('#stock-totals')!.innerHTML=RESOURCES.map(r=>`<span>${icon(RESOURCE[r].icon)} ${Math.floor(s.stock[r])}</span>`).join('');
    const menuKey=JSON.stringify([s.stock,s.milestones,s.deliveries,s.beacon,this.placement]);if(menuKey!==this.menuKey){this.menuKey=menuKey;this.root.querySelector('#build-menu')!.innerHTML=(['drill','smelter','workshop','dock','beacon'] as BuildingType[]).map((type,i)=>{const d=BUILDINGS[type],locked=unlockReason(s,type)||(type==='beacon'&&s.beacon?'Beacon complete':''),afford=canAfford(s.stock,d.cost);return `<button class="build-item ${locked?'locked':''} ${this.placement===type?'chosen':''} ${!afford?'unaffordable':''}" data-action="build" data-type="${type}" ${locked?'disabled':''} title="${locked||d.description}"><span class="build-number">${i+1}</span><span class="build-icon" style="--machine-color:${d.color}">${icon(locked?'lock':d.icon)}</span><strong>${d.name}</strong><span class="costs">${costHtml(d.cost,s)}</span>${locked?`<span class="unlock-hint">${locked}</span>`:''}</button>`;}).join('');}
    const steps=[['First handful','gather'],['Automate extraction','drill'],['Smelt iron ingots','smelter'],['Make your first gears','workshop'],['Bridge to Copperwind','bridge'],['Establish an outpost','outpost'],['Make a drone delivery','drone'],['Light the Sky Beacon','beacon']];const completed=steps.map(([,key])=>key==='bridge'?s.islands[1].unlocked:key==='drone'?s.deliveries>0:key==='beacon'?s.beacon:!!s.milestones[key]);const step=completed.findIndex(v=>!v);const index=step<0?7:step;const descriptions=[`Click the iron outcrop to collect your first ore. Every great factory starts small.`,`Collect 12 ore, commit it to the stockpile, then place an iron drill.`,`Commit 26 ore to build a smelter. Keep local ore for its recipe.`,`Build a workshop with 18 ore + 10 ingots. It presses 3 ingots into a gear.`,`Save 30 ingots + 10 gears in the stockpile, then bridge to Copperwind Reach.`,`Place a drill on Copperwind Reach, paid from your shared stockpile.`,`Build a dock on each island. Select the outpost dock and send surplus ore home.`,`Commit 70 ore, 100 ingots and 55 gears. Upgrade your machines together to bring the beacon closer.`];
    const okey=JSON.stringify([completed,this.checklist]);if(okey!==this.objectiveKey){this.objectiveKey=okey;this.root.querySelector('#objectives')!.innerHTML=`<div class="chapter">${icon(s.beacon?'sparkles':'sun')} CHAPTER 01 <span>${completed.filter(Boolean).length} / 8</span></div><h1>${s.beacon?'A light in the sky':steps[index][0]}</h1><p>${s.beacon?'Your beacon is shining. Keep building, improve your machines, and settle Starfall Isle.':descriptions[index]}</p><div class="objective-progress">${completed.map(v=>`<span class="${v?'done':''}"></span>`).join('')}</div><button class="text-button" data-action="checklist">${this.checklist?'Hide':'View'} journey ${icon('chevron')}</button>${this.checklist?`<ol class="checklist">${steps.map(([name],i)=>`<li class="${completed[i]?'complete':i===index?'current':''}">${completed[i]?icon('check'):`<span>${i+1}</span>`}${name}</li>`).join('')}</ol>`:''}`;}
    for(const spec of ISLANDS){const el=this.root.querySelector<HTMLElement>(`#label-${spec.id}`)!;el.classList.toggle('active',this.island===spec.id);el.querySelector('.island-label-detail')!.innerHTML=s.islands[spec.id].unlocked?`${icon('check')} ${spec.id===this.island?'CURRENT ISLAND':'EXPLORE'}`:`${icon('lock')} ${spec.id===1||s.deliveries>0?'BRIDGE TO EXPAND':'DRONE DELIVERY REQUIRED'}`;}
    const banner=this.root.querySelector<HTMLElement>('#placement-banner')!;banner.hidden=!this.placement;if(this.placement)banner.innerHTML=`${icon(BUILDINGS[this.placement].icon)}<span>Place <strong>${BUILDINGS[this.placement].name}</strong> on a ${canAfford(s.stock,BUILDINGS[this.placement].cost)?'green':'construction'} pad${canAfford(s.stock,BUILDINGS[this.placement].cost)?'':' · Commit more resources first'}</span><button data-action="cancel">Esc ${icon('close')}</button>`;
    const panel=this.root.querySelector<HTMLElement>('#side-panel')!;panel.hidden=!this.panel;if(!this.panel)return;
    const building=s.buildings.find(b=>b.id===this.selected);const pkey=JSON.stringify([this.panel,this.island,this.selected,building&&[building.level,building.paused],s.islands.map(v=>v.unlocked),s.buildings.map(b=>b.id),s.routes.map(r=>[r.id,r.resource,r.target]),s.deliveries>0]);
    if(pkey!==this.panelKey){this.panelKey=pkey;panel.innerHTML=this.panelHTML(s);panel.scrollTop=0;}
    if(this.panel==='building'&&building){const status=panel.querySelector('#machine-status');if(status){status.textContent=machineStatus(s,building);status.classList.toggle('working',building.active);}const progress=panel.querySelector<HTMLElement>('#machine-progress');if(progress)progress.style.width=`${building.progress*100}%`;const runtime=panel.querySelector('#route-runtime');if(runtime){const r=s.routes.find(r=>r.source===building.island);runtime.innerHTML=r?`<span class="status-dot"></span>${r.phase==='outbound'?`In flight · ${r.cargo} ${RESOURCE[r.resource].short.toLowerCase()}`:r.phase==='returning'?'Returning to dock':r.enabled?'Waiting for surplus':'Route paused'}<small>${r.delivered} units delivered${r.phase==='waiting'?'':` · ${Math.max(0,BALANCE.flightSeconds-r.elapsed).toFixed(0)}s to arrival`}</small>`:'Pair this dock with a dock on another island.';}}
    if(this.panel==='stock')for(const r of RESOURCES){panel.querySelector(`#local-${r}`)!.textContent=Math.floor(inv[r]).toString();panel.querySelector(`#stock-${r}`)!.textContent=Math.floor(s.stock[r]).toString();}
    if(this.panel==='map')for(const spec of ISLANDS.slice(1)){const b=panel.querySelector<HTMLButtonElement>(`#expand-${spec.id}`);if(b)b.disabled=!!expansionReason(s,spec.id)||!canAfford(s.stock,spec.cost);}
  }
  invalidate(){this.panelKey='';this.menuKey='';}
  panelHTML(s:GameState):string{const close=`<button class="panel-close icon-button" data-action="close" aria-label="Close panel">${icon('close')}</button>`;
    if(this.panel==='stock')return `${close}<span class="eyebrow">SHARED ACROSS THE SKY</span><h2>Construction stockpile</h2><p>Set aside resources for buildings, upgrades, and bridges. Your machines use the local inventory.</p><div class="inventory-tabs">${ISLANDS.filter(i=>s.islands[i.id].unlocked).map(i=>`<button class="${i.id===this.island?'active':''}" data-action="stock-island" data-island="${i.id}">${i.id===0?'Hearth':i.id===1?'Copperwind':'Starfall'}</button>`).join('')}</div><div class="stock-table"><div class="stock-table-header"><span>RESOURCE</span><span>LOCAL</span><span>HQ</span></div>${RESOURCES.map(r=>`<div class="stock-row"><div>${icon(RESOURCE[r].icon)} ${RESOURCE[r].short}</div><strong id="local-${r}"></strong><strong id="stock-${r}"></strong><button data-action="commit" data-resource="${r}" data-amount="10" title="Commit up to 10 ${RESOURCE[r].short}">+10</button><button data-action="commit" data-resource="${r}" data-amount="all">All ${icon('arrow')}</button></div>`).join('')}</div><button class="primary full" data-action="commit" data-resource="all" data-amount="all">Commit all local resources ${icon('arrow')}</button><p class="note">Keep some ore and ingots local to feed your machines. Committing is one way; construction refunds return here.</p>`;
    if(this.panel==='map')return `${close}<span class="eyebrow">YOUR SKYWARD SETTLEMENT</span><h2>Beyond the horizon</h2><p>Bridges open new building ground. Each island keeps its own inventory.</p>${ISLANDS.map(i=>`<div class="island-card"><div class="island-card-title"><span class="island-number">0${i.id+1}</span><span><h3>${i.name}</h3><small>${i.subtitle}</small></span>${icon(s.islands[i.id].unlocked?'check':'lock')}</div>${s.islands[i.id].unlocked?`<button class="secondary full" data-action="travel" data-island="${i.id}">Explore island ${icon('arrow')}</button>`:`<div class="costs">${costHtml(i.cost)}</div><p class="note">${expansionReason(s,i.id)||'A bridge brings this island within reach.'}</p><button id="expand-${i.id}" class="primary full" data-action="expand" data-island="${i.id}">Construct bridge ${icon('bridge')}</button>`}</div>`).join('')}`;
    if(this.panel==='help')return `${close}<span class="eyebrow">A SMALL FIELD GUIDE</span><h2>Life above the clouds</h2><dl class="controls"><dt>Orbit</dt><dd>Drag with the left mouse button</dd><dt>Zoom</dt><dd>Scroll the mouse wheel</dd><dt>Pan</dt><dd>WASD, arrow keys, or right-drag</dd><dt>Inspect / gather</dt><dd>Click a building or iron deposit</dd><dt>Build</dt><dd>Choose a machine, click a green pad</dd><dt>Cancel / close</dt><dd>Escape</dd><dt>Home view</dt><dd>Click the game title</dd></dl><h3>From ore to opportunity</h3><p>Drills make ore. Smelters turn 2 ore into an ingot. Workshops press 3 ingots into a gear. Production pauses when inputs run out.</p><h3>Two kinds of storage</h3><p>Machines share their island's local inventory. Commit resources to headquarters to pay for construction anywhere. Bridges allow access; paired drone docks move cargo.</p><h3>Cargo with a purpose</h3><p>Select a source dock, destination, resource, and reserve. A drone carries up to 12 surplus units, takes 12 seconds each way, and waits 4 seconds at home.</p><p class="note">Progress saves automatically on this browser. Production rests while the game is closed.</p>`;
    if(this.panel==='settings')return `${close}<span class="eyebrow">MAKE YOURSELF AT HOME</span><h2>Settings</h2><p>Your settlement saves automatically every 5 seconds and after each action.</p><button class="secondary full" data-action="save">${icon('save')} Save now</button><button class="secondary full" data-action="sound">${icon('volume')} Toggle soft machine sounds</button><div class="divider"></div><h3>A fresh patch of sky</h3><p>Reset removes all buildings and progress from this browser.</p><button class="secondary danger full" data-action="reset">${icon('trash')} Reset saved game</button>`;
    const b=s.buildings.find(b=>b.id===this.selected);if(!b)return '';const d=BUILDINGS[b.type];const production=d.cycle>0;
    if(b.type==='hq'){this.panel='stock';return this.panelHTML(s);}
    return `${close}<span class="eyebrow">${ISLANDS[b.island].name.toUpperCase()}</span><div class="machine-title"><span style="--machine-color:${d.color}">${icon(d.icon)}</span><div><h2>${d.name}</h2><span class="level-label">${production?`LEVEL ${b.level} / 3`:'SKY INFRASTRUCTURE'}</span></div></div><p>${d.description}</p><div class="machine-status" id="machine-status"></div>${production?`<div class="production-progress"><span id="machine-progress"></span></div><div class="recipe"><div><span class="tiny-label">INPUT / CYCLE</span><strong>${Object.keys(d.input).length?costHtml(d.input):'Island deposit'}</strong></div>${icon('arrow')}<div><span class="tiny-label">OUTPUT / CYCLE</span><strong>${costHtml(d.output)}</strong></div></div><p class="note">One cycle every ${(d.cycle/LEVEL_MULTIPLIER[b.level]).toFixed(1)}s · Shared local inventory</p><button class="secondary full" data-action="pause-machine">${icon(b.paused?'play':'pause')} ${b.paused?'Resume':'Pause'} production</button><div class="divider"></div>${b.level<3?`<div class="upgrade-header"><h3>Upgrade to level ${b.level+1}</h3><span>+${Math.round((LEVEL_MULTIPLIER[b.level+1]/LEVEL_MULTIPLIER[b.level]-1)*100)}% speed</span></div><div class="costs">${costHtml(upgradeCost(b.type,b.level))}</div><button class="primary full" data-action="upgrade">${icon('plus')} Upgrade machine</button>`:`<div class="max-level">${icon('check')} Fully upgraded</div>`}`:''}
      ${b.type==='dock'?this.routeHTML(s,b.island):''}
      ${b.type==='beacon'?`<div class="beacon-message">${icon('sparkles')} Chapter complete. The horizon is yours.</div>`:''}
      <button class="remove-button" data-action="remove">${icon('trash')} Remove · 60% refund</button>`;
  }
  routeHTML(s:GameState,island:number){const targets=ISLANDS.filter(i=>i.id!==island&&s.buildings.some(b=>b.type==='dock'&&b.island===i.id));const r=s.routes.find(r=>r.source===island);return `<div class="route-status" id="route-runtime"></div>${targets.length?`<form id="route-form"><label>Send cargo to<select name="target">${targets.map(i=>`<option value="${i.id}" ${r?.target===i.id?'selected':''}>${i.name}</option>`).join('')}</select></label><div class="form-row"><label>Resource<select name="resource">${RESOURCES.map(res=>`<option value="${res}" ${r?.resource===res?'selected':''}>${RESOURCE[res].name}</option>`).join('')}</select></label><label>Keep at source<input type="number" min="0" max="99999" step="1" name="reserve" value="${r?.reserve??10}" required/></label></div><p class="note">12 units maximum · 12s flight each way. Change routes when the drone is home.</p><button class="primary full" type="submit">${icon('send')} ${r?'Update route':'Launch cargo route'}</button></form>${r?`<button class="secondary full" data-action="pause-route">${icon(r.enabled?'pause':'play')} ${r.enabled?'Pause':'Resume'} departures</button>`:''}`:`<p class="note">Build a second drone dock on another island to start a cargo route.</p>`}`;}
}
